version: "3"

services:
  clients:
    build:
      context: ./clients
      dockerfile: Dockerfile
    volumes:
      - ./clients:/app
      - /app/node_modules
    ports:
      - "80:80"
    depends_on:
      - flask_app
    restart: always
    environment:
      - REACT_APP_API_URL=http://flask_app:5000/api/v1
    networks:
      - app_network
  flask_app:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/api
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
    restart: always
    networks:
      - app_network

  flask_db:
    container_name: flask_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

volumes:
  pgdata: {}

networks:
  app_network:
    driver: bridge
