version: '3'

services:
  flask_app:
    container_name: flask_app
    image: olatunde2/flask_live_app:1.0.0
    build:
      context: ./server  # This should point to the server directory for the Flask app
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres  # Ensure the DB URL is correct
    volumes:
      - .:/run  # Adjust volume if needed
    depends_on:
      - flask_db
    networks:
      - app_network

  flask_db:
    container_name: flask_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  clients:
    build: ./clients  # This points to the React app directory
    container_name: react_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask_app
    environment:
      - REACT_APP_API_URL=http://flask_app:5000/api/v1  # API URL to Flask app
    networks:
      - app_network

volumes:
  pgdata: {}

networks:
  app_network:
    driver: bridge
